from planners.base import BasePlanner, PlannerResult

class MockPlanner(BasePlanner):
    def run(self, domain, problem):
        mock_plan = """
        ; Mock plan generated by MockPlanner
        0.000: (START)
        1.000: (MOVE A B)
        2.000: (PICKUP ITEM1)
        3.000: (MOVE B C)
        4.000: (DROPOFF ITEM1)
        5.000: (END)
        """
        return PlannerResult(raw_plan=mock_plan)